### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by retr0h** [openstack-ansible-galaxy/openstack-nova_consoleauth#7]
Could we rename the variables from `console_` to `nova_consoleauth` ?  The general rule with roles is to namespace under the role's name.  The namespace `console` is a bit too generic, and could clobber stuff used by something else.  

Also, could we namespace the following as well?  In my deployment, each service has a different rabbit username, password, virtualhost, and having a single namespace for all of this is somewhat confusing.

```
my_ip: "{{ ansible_eth0.ipv4.address }}"

# RabbitMQ
rabbit_hostname: localhost
rabbit_username: rabbit_username_default
rabbit_pass:  rabbit_pass_default
rabbit_virtual_host: /
rabbit_hosts: None
rabbit_ha_queues: false

# Memcached
memcached_servers: None
```

I would envison something like the following.

```
nova_consoleauth_my_ip: "{{ ansible_eth0.ipv4.address }}"

# RabbitMQ
nova_consoleauth_rabbit_hostname: localhost
nova_consoleauth_rabbit_username: rabbit_username_default
nova_consoleauth_rabbit_pass:  rabbit_pass_default
nova_consoleauth_rabbit_virtual_host: /
nova_consoleauth_rabbit_hosts: None
nova_consoleauth_rabbit_ha_queues: false

# Memcached
nova_consoleauth_memcached_servers: None
```

If you choose to use global variables (like you do today) for everything across the deployment you still can, but we need to configure each service by passing what we expect to that service.

```

# Inventory:

my_ip: "{{ ansible_eth0.ipv4.address }}"
rabbit_hostname: localhost
rabbit_username: rabbit_username_default
rabbit_pass:  rabbit_pass_default
rabbit_virtual_host: /
rabbit_hosts: None
rabbit_ha_queues: false
memcached_servers: None

# Deploying

roles:
  - role:  openstack-nova_consoleauth
    nova_consoleauth_my_ip: "{{ my_ip }}"
    nova_consoleauth_rabbit_hostname: "{{ rabbit_hostname }}"
    nova_consoleauth_rabbit_username: "{{ rabbit_username }}"
    nova_consoleauth_rabbit_pass:  "{{ rabbit_pass }}"
    nova_consoleauth_rabbit_virtual_host: "{{ rabbit_virtual_host }}" 
    nova_consoleauth_rabbit_hosts: "{{ rabbit_hosts }}"
    nova_consoleauth_rabbit_ha_queues: "{{ rabbit_ha_queues }}"
    nova_consoleauth_memcached_servers: "{{ memcached_servers }}"
```

The above lets you accomplish what you did before, but you are not clobbering the global namespace, and I am free to configure things on my end the way I choose.
